--[[
  pub-buttons.lua
  Injects BibTeX / PDF / DOI buttons below each .csl-entry.

  Requires pdf_links.json (generated by extract_pdfs.py) in the same
  directory, OR pass --metadata pdf-links="path/to/pdf_links.json".

  At build time the Makefile runs:
    python3 extract_pdfs.py MasterBibliography.bib pdf_links.json
  before pandoc.
]]

-- ── Minimal JSON string-map parser ───────────────────────────
local function parse_json_map(path)
  local map = {}
  local f = io.open(path, "r")
  if not f then
    io.stderr:write("pub-buttons.lua: cannot open " .. tostring(path) .. "\n")
    return map
  end
  local txt = f:read("*a")
  f:close()
  for k, v in txt:gmatch('"([^"]+)"%s*:%s*"([^"]+)"') do
    map[k] = v
  end
  return map
end

-- ── Parse raw BibTeX entries from .bib ───────────────────────
local function parse_bib_raw(path)
  local entries = {}
  local f = io.open(path, "r")
  if not f then return entries end
  local txt = f:read("*a")
  f:close()

  local pos = 1
  while true do
    local s, e, etype, key = txt:find("@(%w+)%s*{%s*([^,%s]+)%s*,", pos)
    if not s then break end
    if not etype:lower():match("^(string|preamble|comment)$") then
      local depth = 1
      local i = e + 1
      while i <= #txt and depth > 0 do
        local c = txt:sub(i,i)
        if     c == "{" then depth = depth + 1
        elseif c == "}" then depth = depth - 1 end
        i = i + 1
      end
      -- Strip noisy fields for clean BibTeX display
      local raw = txt:sub(s, i - 1)
      raw = raw:gsub("%s*bdsk%-file%-%d+%s*=%s*%b{}%s*,?%s*\n?", "\n")
      raw = raw:gsub("%s*bdsk%-url%-%d+%s*=%s*%b{}%s*,?%s*\n?", "\n")
      raw = raw:gsub("%s*date%-added%s*=%s*%b{}%s*,?%s*\n?", "\n")
      raw = raw:gsub("%s*date%-modified%s*=%s*%b{}%s*,?%s*\n?", "\n")
      raw = raw:gsub("\n\n+", "\n")
      -- Extract doi
      local doi = raw:match("[Dd][Oo][Ii]%s*=%s*[{\"](.-)[}\"]")
      doi = doi and doi:gsub("%s+","") or nil
      entries[key] = { raw = raw, doi = doi }
    end
    pos = e + 1
  end
  return entries
end

-- ── CSS + JS (injected once) ──────────────────────────────────
local function make_styles()
  return pandoc.RawBlock("html", [[
<style>
.pub-btn-row {
  padding-left:  2em;
  margin-top:    2pt;
  margin-bottom: 8pt;
  display:       flex;
  gap:           5pt;
  flex-wrap:     wrap;
}
.pub-btn {
  font-size:       8.5pt;
  padding:         1.5pt 8pt;
  border:          1pt solid currentColor;
  border-radius:   3px;
  cursor:          pointer;
  background:      transparent;
  text-decoration: none;
  display:         inline-block;
  transition:      background 0.15s, color 0.15s;
  font-family:     var(--font, inherit);
}
.btn-bib { color: var(--groy, #057AB2); }
.btn-bib:hover { background: var(--groy, #057AB2); color: #fff; }
.btn-pdf { color: #C90016; }
.btn-pdf:hover { background: #C90016; color: #fff; }
.btn-doi { color: var(--my-gray, #a6a6a6); }
.btn-doi:hover { background: var(--my-gray, #a6a6a6); color: #fff; }
/* ── BibTeX lightbox ── */
.bib-overlay {
  display:         none;
  position:        fixed;
  inset:           0;
  background:      rgba(0,0,0,0.55);
  z-index:         9999;
  align-items:     center;
  justify-content: center;
  padding:         1.5rem;
}
.bib-overlay.open { display: flex; }
.bib-box {
  background:     #fff;
  border-radius:  6px;
  max-width:      680px;
  width:          100%;
  max-height:     80vh;
  display:        flex;
  flex-direction: column;
  box-shadow:     0 8px 40px rgba(0,0,0,0.28);
  overflow:       hidden;
}
.bib-box-header {
  display:         flex;
  align-items:     center;
  justify-content: space-between;
  padding:         10px 14px 8px;
  border-bottom:   1px solid #e0e0e0;
  font-size:       9pt;
  font-weight:     600;
  color:           var(--groy, #057AB2);
  font-family:     var(--font, inherit);
}
.bib-close {
  background:  none;
  border:      none;
  cursor:      pointer;
  font-size:   16px;
  color:       #888;
  line-height: 1;
  padding:     0 2px;
}
.bib-close:hover { color: #333; }
.bib-copy {
  font-size:     8pt;
  padding:       2pt 8pt;
  border:        1pt solid var(--groy, #057AB2);
  border-radius: 3px;
  cursor:        pointer;
  background:    transparent;
  color:         var(--groy, #057AB2);
  font-family:   var(--font, inherit);
  transition:    background 0.15s, color 0.15s;
}
.bib-copy:hover { background: var(--groy, #057AB2); color: #fff; }
.bib-box pre {
  font-family: 'Courier New', monospace;
  font-size:   8pt;
  padding:     12px 16px;
  overflow:    auto;
  white-space: pre;
  line-height: 1.5;
  margin:      0;
  flex:        1;
}
@media print { .pub-btn-row, .bib-overlay { display: none !important; } }
</style>
<div id="bib-lightbox" class="bib-overlay" onclick="if(event.target===this)closeBib()">
  <div class="bib-box">
    <div class="bib-box-header">
      <span>BibTeX</span>
      <div style="display:flex;gap:8px;align-items:center">
        <button class="bib-copy" onclick="copyBib()">Copy</button>
        <button class="bib-close" onclick="closeBib()">&#x2715;</button>
      </div>
    </div>
    <pre id="bib-lightbox-content"></pre>
  </div>
</div>
<script>
function showBib(id) {
  var src = document.getElementById(id);
  if (!src) return;
  document.getElementById('bib-lightbox-content').textContent = src.textContent;
  document.getElementById('bib-lightbox').classList.add('open');
}
function closeBib() {
  document.getElementById('bib-lightbox').classList.remove('open');
}
function copyBib() {
  var txt = document.getElementById('bib-lightbox-content').textContent;
  navigator.clipboard.writeText(txt).then(function() {
    var btn = document.querySelector('.bib-copy');
    btn.textContent = 'Copied!';
    setTimeout(function(){ btn.textContent = 'Copy'; }, 1500);
  });
}
document.addEventListener('keydown', function(e) { if (e.key==='Escape') closeBib(); });
</script>
]])
end

-- ── Main ──────────────────────────────────────────────────────
function Pandoc(doc)
  -- Resolve paths from metadata
  local bib_path  = ""
  local json_path = "pdf_links.json"

  if doc.meta["bibliography"] then
    bib_path = pandoc.utils.stringify(doc.meta["bibliography"])
  end
  if doc.meta["bib-file"] then
    bib_path = pandoc.utils.stringify(doc.meta["bib-file"])
  end
  if doc.meta["pdf-links"] then
    json_path = pandoc.utils.stringify(doc.meta["pdf-links"])
  end

  local pdf_links = parse_json_map(json_path)
  local bib_data  = bib_path ~= "" and parse_bib_raw(bib_path) or {}

  local n_pdf = 0
  for _ in pairs(pdf_links) do n_pdf = n_pdf + 1 end
  io.stderr:write(string.format(
    "pub-buttons.lua: %d PDF links, %d bib entries\n",
    n_pdf, (function() local c=0 for _ in pairs(bib_data) do c=c+1 end return c end)()))

  local styles_injected = false
  local new_blocks = {}

  for _, block in ipairs(doc.blocks) do
    table.insert(new_blocks, block)

    local is_refs = block.t == "Div" and (
      block.attr.identifier == "refs" or
      block.attr.identifier == "refs-books" or
      block.attr.identifier == "refs-chapters" or
      block.attr.identifier == "refs-theses")

    if is_refs then
      if not styles_injected then
        -- Insert styles before this div
        table.insert(new_blocks, #new_blocks, make_styles())
        styles_injected = true
      end

      local new_content = {}
      for _, entry in ipairs(block.content) do
        -- Pass through raw blocks (year headers etc)
        if entry.t ~= "Div" then
          table.insert(new_content, entry)
        else
          -- Check if csl-entry
          local is_entry = false
          for _, c in ipairs(entry.attr.classes) do
            if c == "csl-entry" then is_entry = true; break end
          end
          table.insert(new_content, entry)

          if is_entry then
            local id  = entry.attr.identifier        -- "ref-cheng2026"
            local key = id:gsub("^ref%-", "")        -- "cheng2026"
            local pdf = pdf_links[key]
            local bib = bib_data[key]
            local doi = bib and bib.doi or nil
            local bib_id = "bibpop-" .. key

            -- Button row
            local row = '<div class="pub-btn-row">'
            row = row .. string.format(
              '<button class="pub-btn btn-bib" onclick="showBib(\'%s\')">BibTeX</button>',
              bib_id)
            if pdf then
              row = row .. string.format(
                '<a class="pub-btn btn-pdf" href="%s" target="_blank">PDF</a>', pdf)
            end
            if doi then
              row = row .. string.format(
                '<a class="pub-btn btn-doi" href="https://doi.org/%s" target="_blank">DOI</a>',
                doi)
            end
            row = row .. '</div>'

            -- BibTeX popup
            local raw_escaped = bib and bib.raw
              :gsub("&","&amp;"):gsub("<","&lt;"):gsub(">","&gt;")
              or "(entry not found)"
            local popup = string.format(
              '<div id="%s" style="display:none">%s</div>',
              bib_id, raw_escaped)

            table.insert(new_content, pandoc.RawBlock("html", row))
            table.insert(new_content, pandoc.RawBlock("html", popup))
          end
        end
      end

      new_blocks[#new_blocks] = pandoc.Div(new_content,
        pandoc.Attr(block.attr.identifier, block.attr.classes, block.attr.attributes))
    end
  end

  doc.blocks = new_blocks
  return doc
end