backend:
  name: github
  repo: harshasbhat/harshasbhat.github.io
  branch: master
  site_domain: relaxed-swanson-d4ba6c.netlify.com

media_folder: "images/"

collections:
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: " " # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
