backend:
  name: github
  repo: harshasbhat/harshasbhat.github.io
  branch: master
  site_domain: harshasbhat.netlify.com

media_folder: "images/"

collections:
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
